version: 0.2

phases:
  pre_build:
    commands:
      - mvn clean install
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 183295441285.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t expenselens_backend .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker tag expenselens_backend:latest 183295441285.dkr.ecr.us-east-1.amazonaws.com/expenselens_backend:latest
      - docker push 183295441285.dkr.ecr.us-east-1.amazonaws.com/expenselens_backend:latest
      

artifacts:
  files:
    - imagedefinitions.json
    - target/course-service.jar
